services:
    laravel.test:
        container_name: lotto_app
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
        image: sail-8.2/app
        ports:
            - "${APP_PORT:-80}:80"
        environment:
            WWWUSER: '${WWWUSER}'
            WWWGROUP: '${WWWGROUP}'
            LARAVEL_SAIL: 1
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - mariadb

    mariadb:
        image: 'mariadb:10'
        container_name: lotto_db
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ['CMD', 'mariadb-admin', 'ping', '-h', 'localhost', '-u', 'root', '-p${DB_PASSWORD}']
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge

volumes:
    sail-mariadb:
        driver: local
